# Generated by Django 3.2.9 on 2021-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
