# Generated by Django 3.2.9 on 2021-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20211122_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='view_status',
            field=models.CharField(default='pendding', max_length=100),
        ),
    ]
