# Generated by Django 3.2.9 on 2021-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_share_view_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='share',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
