# Generated by Django 3.2.9 on 2021-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mail_sent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
