# Generated by Django 3.2.9 on 2021-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20211127_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
